export const subscriptionsSymbols = {
  NEW_SOLAR_DAY_SUBSCRIPTION: Symbol('NEW_SOLAR_DAY_SUBSCRIPTION'),
  NEW_QIYAM_SUBSCRIPTION: Symbol('NEW_QIYAM_SUBSCRIPTION'),
  ADHAN_SUBSCRIPTION: Symbol('ADHAN_SUBSCRIPTION'),
}
